# -*- coding: utf-8 -*-
"""Exercicio-01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CxmmcZYZLf4SgT_D_cKc_NiNMSkgNCqx
"""

type (1)

# Int = número inteiro

type (True)

# Bool = valor lógico verdadeiro

type (5/2)

# Float = número flutuante

type (2.5)

# Float = número flutuante

type (False)

# False = valor lógico verdadeiro

type (5+3j)

#Complex = número complexo