# -*- coding: utf-8 -*-
"""Exercicio.04

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N6lkMJcY1PayDdV4RI7zAwj35Sw7VBzT
"""

# COORDENADAS DE LATITUDE E LONGITUDE DE DOIS PONTOS:

longitude1 = float(input("valor de longitude1 = "))

type(longitude1)

latitude1 = float(input("valor de latitude1 = "))

longitude2 = float(input("valor de longitude2 = "))

latitude2 = float(input("valor de latitude2 = "))

# FÓRMULA DE HAVERSINE

import math

# TRANFORMANDO GRAUS DECIMAIS EM RADIANO DOS VALORES DE LATITUDE

x1 = math.degrees(latitude1)
print(x1)

x2 = math.degrees(latitude2)
print(x2)

#PRIMEIRA EQUAÇÃO DENTRO DA RAIZ

A = math.sin((x2-x1)/2)**2 
print(A)

# TRANSFORMANDO GRAUS DECIMAIS EM RADIANO DOS VALORES DE LONGITUDE

y1 = math.degrees(longitude1)
print(y1)

y2 = math.degrees(longitude2)
print (y2)

# SEGUNDA EQUAÇÃO DE DENTRO DA RAIZ

B = math.sin((y2-y1)/2)**2 
print (B)

#MULTIPLICAÇÃO DOS COSSENOS DAS LATITUDES

CL1 = math.cos(x1)
print(CL1)

CL2 = math.cos(x2)
print(CL2)

#EQUAÇÃO DE DENTRO DA RAIZ

DR = A+(CL1*CL2*B)
print (DR)

#RESULTADO DA RAIZ

R = math.sqrt(DR)
print(R)

#EQUAÇÃO TOTAL

H = 2*6371*(math.asin(R))
print(H)