# -*- coding: utf-8 -*-
"""Exercicio -02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Op7STmTHgftcOrTamKJchA7qzgpMEcSp
"""

x1 = 5/2 
print(x, type(x))

# Operação de divisão, tendo como reusultado o valor 2.5 do tipo float

x2 = 7 * 4 + 2 
print(x2, type(x2))

# Equação, tendo como resultado o valor 30, do tipo int

x3 = (7 * 4) + 2   
print(x3, type(x3))

# Equação, tendo como resultado o valor 30, do tipo int

x4 = 7 * (4 + 2)    
print(x4, type(x4))

# Equação, tendo como resultado o valor 42, do tipo int

x5 = 2 ** 3    
print(x5, type(x5))

# Exponencial, tendo como resultado o valor 8, do tipo int

x6 = 2 ** 3 ** 4   
print(x6, type(x6))

# Exponencial, tendo como resultado o valor 2417851639229258349412352, do tipo int

x7 = 2 ** -3 ** 4  
print(x7, type(x7))

# Exponencial, tendo como resultado o valor 4.1359030627651384e-25, do tipo float

x8 = 5 % 2   
print(x8, type(x8))

# Valor do resto da divisão, tendo como resultado o valor 1, do tipo int

x9 = 6 % 2 
print(x9, type(x9))

# Valor do resto da divisão, tendo como resultado o valor 0, do tipo int

x10 = 7 % 2   
print(x10, type(x10))

# Valor do resto da divisão, tendo como resultado o valor 1, do tipo int

x11 = 8 % 2  
print(x11, type(x11))

# Valor do resto da divisão, tendo como resultado o valor 0, do tipo int

x12 = 5 + 1  
print(x12, type(x12))

# Operação de soma, tendo como resultado o valor 6, do tipo int

x13 = 5.0 + 1    
print(x13, type(x13))

# Operação de soma, tendo como resultado o valor 6.0, do tipo float

import math #Importação da biblioteca "math"

x14 = 5 * math.log10(100) - 8 ** 2  
print(x14, type(x14))

# Equação com aplicação do logarítimo da biblioteca math, tendo como resultado o valor -54.0, do tipo float

x15 = math.pi            
print(x15, type(x15))

# Númeoro pi com aplicação da biblioteca math, tendo como resultado o valor 3.141592653589793, do tipo float

x16 = math.sin(math.pi / 2 )     #Equação com aplicação de seno
print(x16, type(x16))

# Equação com aplicação do seno da biblioteca math, tendo como resultado o valor 1.0, do tipo float

x17 = math.cos(math.pi / 4 ) #Equação com aplicação de cosseno
print(x17, type(x17))

# Equação com aplicação do cosseno da biblioteca math, tendo como resultado o valor 0.7071067811865476, do tipo float